### ISSUE TITLE
When `friend` is created it deletes oneself 

### ISSUE THREAD

**Issue by MoonRainy21** [SSHS-pebble/seat-backend#6]
`/friend`에 `PUT`요청을 넣어서 타인을 friend로 추가하면 `/friend?from=uid`가 원래 자기자신이 있던 길이 1의 리스트에서 추가된 하나의 사람만 존재하는 리스트로 변화.
이 시점에 `/friend?to=uid`를 하면 여전히 자기자신이 되기 때문에 from과 to 사이의 괴리가 존재하게 됨. 
또, 내가 프엔에 pull 리퀘한 부분이 이석신청 부분에서
자기 자신이 스스로의 친구기 때문에 자기 이름이 두번 등장하는 버그였는데, 이렇게 friend가 작동하면 자기 자신의 이름이 사라짐.
프엔에서 처리하는 방법도 있겠지만 백엔에서 스스로를 삭제하지 않는 편이 좋은듯..?

**Comment by hamerin** [comment]
Fixed in a234590
